"""add streaming api models

Revision ID: 4104e0274dd2
Revises:
Create Date: 2025-12-02 21:35:51.397708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4104e0274dd2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("country_code"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("home_page", sa.String(), nullable=False),
        sa.Column("theme_color_code", sa.String(), nullable=False),
        sa.Column("image_set", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "streaming_option_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("show_type", sa.Enum("MOVIE", "SERIES", name="showtype"), nullable=False),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("tmdb_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("original_title", sa.String(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("first_air_year", sa.Integer(), nullable=True),
        sa.Column("last_air_year", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("season_count", sa.Integer(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("directors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("creators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cast", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "addons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("home_page", sa.String(), nullable=False),
        sa.Column("theme_color_code", sa.String(), nullable=False),
        sa.Column("image_set", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country_services",
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.country_code"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("country_code", "service_id"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.String(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("first_air_year", sa.Integer(), nullable=True),
        sa.Column("last_air_year", sa.Integer(), nullable=True),
        sa.Column("streaming_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "show_genres",
        sa.Column("show_id", sa.String(), nullable=False),
        sa.Column("genre_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("show_id", "genre_id"),
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "change_type",
            sa.Enum("NEW", "REMOVED", "UPDATED", "EXPIRING", "UPCOMING", name="changetype"),
            nullable=False,
        ),
        sa.Column(
            "item_type", sa.Enum("SHOW", "SEASON", "EPISODE", name="itemtype"), nullable=False
        ),
        sa.Column("show_id", sa.String(), nullable=False),
        sa.Column("show_type", sa.Enum("MOVIE", "SERIES", name="showtype"), nullable=False),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column(
            "streaming_option_type",
            sa.Enum("SUBSCRIPTION", "FREE", "RENT", "BUY", "ADDON", name="streamingoptiontype"),
            nullable=False,
        ),
        sa.Column("addon_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["addon_id"],
            ["addons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("air_year", sa.Integer(), nullable=True),
        sa.Column("streaming_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "streaming_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SUBSCRIPTION", "FREE", "RENT", "BUY", "ADDON", name="streamingoptiontype"),
            nullable=False,
        ),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("video_link", sa.String(), nullable=True),
        sa.Column("quality", sa.Enum("SD", "HD", "QHD", "UHD", name="quality"), nullable=True),
        sa.Column("audios", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("subtitles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("price", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("addon_id", sa.String(), nullable=True),
        sa.Column("expires_soon", sa.Boolean(), nullable=False),
        sa.Column("available_since", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["addon_id"],
            ["addons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("streaming_options")
    op.drop_table("episodes")
    op.drop_table("changes")
    op.drop_table("show_genres")
    op.drop_table("seasons")
    op.drop_table("country_services")
    op.drop_table("addons")
    op.drop_table("shows")
    op.drop_table("services")
    op.drop_table("genres")
    op.drop_table("countries")
    # ### end Alembic commands ###
