"""

Revision ID: 4b6b35253fef
Revises: ee91dc87304d
Create Date: 2025-12-06 22:16:24.104366

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4b6b35253fef"
down_revision: str | None = "ee91dc87304d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
