"""update scraped tables schema remove fk add tmdb_id and details

Revision ID: 538bc24b19b4
Revises: bdb209c95047
Create Date: 2025-12-07 12:58:35.219387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "538bc24b19b4"
down_revision: str | None = "bdb209c95047"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scraped_popular_shows", sa.Column("tmdb_id", sa.String(), nullable=True))
    op.add_column(
        "scraped_popular_shows",
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_constraint(
        op.f("scraped_popular_shows_show_id_fkey"), "scraped_popular_shows", type_="foreignkey"
    )
    op.drop_column("scraped_popular_shows", "show_id")
    op.alter_column("scraped_shows", "tmdb_id", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_scraped_shows_tmdb_id"), "scraped_shows", ["tmdb_id"], unique=False)
    op.add_column("scraped_top_shows", sa.Column("tmdb_id", sa.String(), nullable=True))
    op.add_column(
        "scraped_top_shows",
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_constraint(
        op.f("scraped_top_shows_show_id_fkey"), "scraped_top_shows", type_="foreignkey"
    )
    op.drop_column("scraped_top_shows", "show_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraped_top_shows", sa.Column("show_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("scraped_top_shows_show_id_fkey"),
        "scraped_top_shows",
        "scraped_shows",
        ["show_id"],
        ["id"],
    )
    op.drop_column("scraped_top_shows", "details")
    op.drop_column("scraped_top_shows", "tmdb_id")
    op.drop_index(op.f("ix_scraped_shows_tmdb_id"), table_name="scraped_shows")
    op.alter_column("scraped_shows", "tmdb_id", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "scraped_popular_shows",
        sa.Column("show_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("scraped_popular_shows_show_id_fkey"),
        "scraped_popular_shows",
        "scraped_shows",
        ["show_id"],
        ["id"],
    )
    op.drop_column("scraped_popular_shows", "details")
    op.drop_column("scraped_popular_shows", "tmdb_id")
    # ### end Alembic commands ###
