"""

Revision ID: 708963fd497d
Revises: ef9578c4882d
Create Date: 2025-12-06 20:25:19.743720

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "708963fd497d"
down_revision: str | None = "ef9578c4882d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
