"""add origin_urls to shows

Revision ID: 7122ba21f393
Revises: 4104e0274dd2
Create Date: 2025-12-06 16:58:26.500284

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7122ba21f393"
down_revision: str | None = "4104e0274dd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shows", sa.Column("origin_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shows", "origin_urls")
    # ### end Alembic commands ###
