"""

Revision ID: acc3f4953c2f
Revises: 538bc24b19b4
Create Date: 2025-12-07 13:20:08.073818

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "acc3f4953c2f"
down_revision: str | None = "538bc24b19b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
