"""

Revision ID: c4c4c1257969
Revises: da6082569c25
Create Date: 2025-12-07 14:54:05.000888

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c4c4c1257969"
down_revision: str | None = "da6082569c25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
