"""add scraped_popular_shows table

Revision ID: cf53ddd23131
Revises: 4b6b35253fef
Create Date: 2025-12-06 22:38:50.663547

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf53ddd23131"
down_revision: str | None = "4b6b35253fef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scraped_popular_shows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("show_type", sa.String(), nullable=False),
        sa.Column("batch_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["scraped_shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scraped_popular_shows_batch_sequence",
        "scraped_popular_shows",
        ["batch_sequence"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scraped_popular_shows_batch_sequence", table_name="scraped_popular_shows")
    op.drop_table("scraped_popular_shows")
    # ### end Alembic commands ###
