"""

Revision ID: d048f8ef2fce
Revises: edae29fc2cd8
Create Date: 2025-12-07 15:24:03.297625

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d048f8ef2fce"
down_revision: str | None = "edae29fc2cd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
