"""add needs_review to scraped_shows

Revision ID: da6082569c25
Revises: acc3f4953c2f
Create Date: 2025-12-07 14:50:42.900377

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da6082569c25"
down_revision: str | None = "acc3f4953c2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scraped_shows", sa.Column("needs_review", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraped_shows", "needs_review")
    # ### end Alembic commands ###
