"""add validation_status and confidence to scraped tables

Revision ID: e25e65df4744
Revises: d048f8ef2fce
Create Date: 2025-12-07 17:00:26.370962

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e25e65df4744"
down_revision: str | None = "d048f8ef2fce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraped_popular_shows",
        sa.Column("validation_status", sa.String(), server_default="not_started", nullable=False),
    )
    op.add_column("scraped_popular_shows", sa.Column("confidence", sa.Integer(), nullable=True))
    op.add_column(
        "scraped_top_shows",
        sa.Column("validation_status", sa.String(), server_default="not_started", nullable=False),
    )
    op.add_column("scraped_top_shows", sa.Column("confidence", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraped_top_shows", "confidence")
    op.drop_column("scraped_top_shows", "validation_status")
    op.drop_column("scraped_popular_shows", "confidence")
    op.drop_column("scraped_popular_shows", "validation_status")
    # ### end Alembic commands ###
