"""add unique constraint to scraped_shows tmdb_id

Revision ID: edae29fc2cd8
Revises: c4c4c1257969
Create Date: 2025-12-07 15:22:58.847707

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edae29fc2cd8"
down_revision: str | None = "c4c4c1257969"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scraped_shows_tmdb_id"), table_name="scraped_shows")
    op.create_index(op.f("ix_scraped_shows_tmdb_id"), "scraped_shows", ["tmdb_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scraped_shows_tmdb_id"), table_name="scraped_shows")
    op.create_index(op.f("ix_scraped_shows_tmdb_id"), "scraped_shows", ["tmdb_id"], unique=False)
    # ### end Alembic commands ###
